-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 08:25:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  `Data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `nome` VARCHAR(45) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `matricula` FLOAT NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Pagamento_idPagamento`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Cliente_Pagamento1_idx` (`Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `IdAula` INT NOT NULL,
  `Horario` TIME NOT NULL,
  `Instrutor` VARCHAR(45) NOT NULL,
  `TipoAula` VARCHAR(45) NOT NULL,
  `Cliente_cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`IdAula`, `Cliente_cpf`),
  UNIQUE INDEX `IdAula_UNIQUE` (`IdAula` ASC) VISIBLE,
  INDEX `fk_Aula_Cliente1_idx` (`Cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Aula_Cliente1`
    FOREIGN KEY (`Cliente_cpf`)
    REFERENCES `mydb`.`Cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instrutor` (
  `Nome` VARCHAR(50) NOT NULL,
  `IdInstrutor` CHAR(5) NOT NULL,
  `epecInstrutor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intrutor_Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Intrutor_Aula` (
  `Instrutor_IdInstrutor` CHAR(5) NOT NULL,
  `Aula_IdAula` INT NOT NULL,
  PRIMARY KEY (`Instrutor_IdInstrutor`, `Aula_IdAula`),
  INDEX `fk_Instrutor_has_Aula_Aula1_idx` (`Aula_IdAula` ASC) VISIBLE,
  INDEX `fk_Instrutor_has_Aula_Instrutor_idx` (`Instrutor_IdInstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_Intrutor_aula`
    FOREIGN KEY (`Instrutor_IdInstrutor`)
    REFERENCES `mydb`.`Instrutor` (`IdInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_aula_aluno`
    FOREIGN KEY (`Aula_IdAula`)
    REFERENCES `mydb`.`Aula` (`IdAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acesso` (
  `idAcesso` INT NOT NULL,
  `Data_pagamento` DATE NOT NULL,
  `Cliente_cpf` CHAR(11) NOT NULL,
  `Cliente_Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idAcesso`, `Cliente_cpf`, `Cliente_Pagamento_idPagamento`),
  INDEX `fk_Acesso_Cliente1_idx` (`Cliente_cpf` ASC, `Cliente_Pagamento_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Acesso_Cliente1`
    FOREIGN KEY (`Cliente_cpf` , `Cliente_Pagamento_idPagamento`)
    REFERENCES `mydb`.`Cliente` (`cpf` , `Pagamento_idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
